# -*- coding: utf-8 -*-
"""tsneRania.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JQEnXr2ac8xK0_T31UsyWDqxdKHoJNc6
"""

import pandas as pd
#df_train= pd.read_csv("eclipse_train_SBert.csv")
df_test= pd.read_csv("/content/Rania_Training.csv")

df_test.head()

#t= df_test.to_numpy()
#import numpy as np
#np.any(np.isnan(t))

#te= df_test.fillna(0)

#te.head()

from sklearn.manifold import TSNE
m=TSNE(learning_rate=50, verbose=1)
#features= m.fit_transform(df_numeric)

tsne_em = m.fit_transform(df_test)

pip install bioinfokit

#test_labels= te["Label"]
#test_features=te.drop(columns=['Label'], axis=1)

test_labels= df_test["Label"]
test_features=df_test.drop(columns=['Label'], axis=1)

import matplotlib.pyplot as plt
import seaborn as snsplt

#plot t-SNE clusters
from bioinfokit.visuz import cluster
cluster.tsneplot(score=tsne_em)

#plt.show()


 #☺get a list of categories
color_class = test_labels.to_numpy()#testLabels#df['class'].to_numpy()
cluster.tsneplot(score=tsne_em, colorlist=color_class, colordot=('#b0413e', '#4381c1'),
    legendpos='upper right')